nama=("NAUFAL RAHISNA")
jk=("Laki-Laki")
agama=("Islam")
ttl=("Praya, 07 Mei 2002")
Alamat=("Amen")
hobi=("Game, Editing")
Prodi=("Teknik Informatika")
Nim=("TI20230034")
smt=int(2)
Angkt=int(2023)
sts=("Aktif")
wa=int(+6281999533255)
ig=("@itsfal.r")
Ytb=("Novra")
email=("naufalrahisna501@gmail.com")
tk=("TK Taman Bahagia")
sd=("SD Negeri 1 tengari")
smp=("SMP Negeri 2 Praya")
sma=("SMA Negeri 1 Praya")
pg=("STMIK Lombok")


print("|  BIODATA PRIBADI  |")
print("-----------------------------")
print(" ")
print("Nama                    = ",nama)
print("Jenis Kelamin           = ",jk)
print("Agama                   = ",agama)
print("Tempat, tanggal lahir   = ",ttl)
print("Alamat                  = ",Alamat)
print("Hobi                    = ",hobi)
print(" ")
print("|  SOSIAL MEDIA  |")
print("-----------------------------")
print(" ")
print("WhatsApp         = ",wa)
print("Instagram        = ",ig)
print("Youtube          = ",Ytb)
print("Email            = ",email)
print(" ")
print("|  PERGURUAN TINGGI  |")
print("-----------------------------")
print(" ")
print("Kampus            = ",pg)
print("Prodi/Jurusan     = ",Prodi)
print("NIM               = ",Nim)
print("Semester          = ",smt)
print("Angkatan          = ",Angkt)
print("Status Mahasiswa  = ",sts)
print(" ")
print("|  PENDIDIKAN  |")
print("-----------------------------")
print(" ")
print("SD     = ",sd)
print("SMP    = ",smp)
print("SMA    = ",sma)
print(" ")
print("--------------------------------------------------")
print("|  TERIMAKASIH SUDAH MAMPIR, JANGAN LUPA FOLLOW  |")
print("--------------------------------------------------")
print(" ")



